services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mongo
      - minio
    volumes:
      - .:/app
    environment:
      MONGO_HOST: mongo
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
    networks:
      - mynetwork
  
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    networks:
      - mynetwork

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root123
      ME_CONFIG_MONGODB_SERVER: mongo
      
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    networks:
      - mynetwork

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"   
      # - "9001:9001"  
    volumes:
      - minio_data:/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  minio_data:
  mongo_data:
